version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - unq-relayer-network
  relayer:
    build:
      context: .
    container_name: unq-relayer
    image: wormhole-relayer
    networks:
      - unq-relayer-network
    ports:
      - 3003:3003
    command: npm run start:prod
    depends_on:
    - redis
networks:
  unq-relayer-network:
    driver: bridge

 
    
